lim:
  tcpPort: 9001
  webSocketPort: 19001
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000 # 心跳超时时间 ms
  brokerId: 1001
  redis:
    mode: single
    database: 1
#    password: 123456
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    single :
      address: 192.168.192.129:6379
  rabbitmq:
    host: 192.168.192.129
    port: 5672
    virtualHost: /
    userName: crystal
    password: 7355608
  zkConfig:
    zkAddr: 192.168.192.129:2181
    zkConnectTimeOut: 5000