lim:
  tcpPort: 9001
  webSocketPort: 19001
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000 # 心跳超时时间 ms
  brokerId: 1000
  loginModel: 1 #登陆模式 后期改成表
  #  *                多端同步模式：1 只允许一端在线，手机/电脑/web 踢掉除了本client+imel的设备
  #  *                            2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imel的非web端设备
  #  *                            3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imel的同端设备
  #  *                            4 允许所有端多设备登录 不踢任何设备
  logicUrl: http://127.0.0.1:8000/v1
  redis:
    mode: single
    database: 1
    #    password: 123456
    timeout: 3000
    poolMinIdle: 8
    poolConnTimeout: 3000
    poolSize: 10
    single :
      address: 192.168.192.129:6379
  rabbitmq:
    host: 192.168.192.129
    port: 5672
    virtualHost: /
    userName: crystal
    password: 7355608
  zkConfig:
    zkAddr: 192.168.192.129:2181
    zkConnectTimeOut: 5000