spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.192.129:3306/im_data?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: root
#logging:
#  config: classpath:logback-spring.xml
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl